-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 29, 2025 at 02:21 PM
-- Server version: 5.7.44
-- PHP Version: 8.1.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `lovei1_engageeventmanager`
--

-- --------------------------------------------------------

--
-- Table structure for table `admins`
--

CREATE TABLE `admins` (
  `AID` int(11) NOT NULL,
  `email` varchar(40) NOT NULL,
  `password` varchar(40) NOT NULL,
  `first_name` varchar(15) NOT NULL,
  `last_name` varchar(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admins`
--

INSERT INTO `admins` (`AID`, `email`, `password`, `first_name`, `last_name`) VALUES
(1, 'adminemail@gmail.com', 'efacc4001e857f7eba4ae781c2932dedf843865e', 'Ian', 'Love');

-- --------------------------------------------------------

--
-- Table structure for table `events`
--

CREATE TABLE `events` (
  `Name` varchar(150) NOT NULL,
  `Organization` varchar(75) NOT NULL,
  `Description` varchar(2500) NOT NULL,
  `TimeStart` datetime NOT NULL,
  `TimeEnd` datetime NOT NULL,
  `EID` int(11) NOT NULL,
  `Location` varchar(150) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `events`
--

INSERT INTO `events` (`Name`, `Organization`, `Description`, `TimeStart`, `TimeEnd`, `EID`, `Location`) VALUES
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 11:30 a.m. - 12:15 p.m. \n Student Recreation Center Pool', '2025-06-22 15:30:00', '2025-06-22 17:30:00', 1641, 'Student Recreation Center Pool'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 12:30 p.m. - 1:15 p.m. \n Student Recreation Center Pool', '2025-06-22 16:30:00', '2025-06-22 18:30:00', 1642, 'Student Recreation Center Pool'),
('Learn to Swim - 8 to 13 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 10:30 a.m. - 11:15 a.m. \n Student Recreation Center Pool', '2025-06-22 14:30:00', '2025-06-22 16:30:00', 1640, 'Student Recreation Center Pool'),
('Learn to Swim - Adults ', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $40-$50 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 9:30 a.m. - 10:15 a.m. \n Student Recreation Center Pool', '2025-06-22 13:30:00', '2025-06-22 15:30:00', 1639, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 12 p.m. - 12:45 p.m. \n Student Recreation Center Pool', '2025-06-21 16:00:00', '2025-06-21 18:00:00', 1638, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 8 to 13 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 11 a.m. - 11:45 a.m. \n Student Recreation Center Pool', '2025-06-21 15:00:00', '2025-06-21 17:00:00', 1637, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Registration opens March 3 \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 10 a.m. - 10:45 a.m. \n Student Recreation Center Pool', '2025-06-21 14:00:00', '2025-06-21 16:00:00', 1636, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 12:30 p.m. - 1:15 p.m. \n Student Recreation Center Pool', '2025-06-15 16:30:00', '2025-06-15 18:30:00', 1634, 'Student Recreation Center Pool'),
('Learn to Swim - Adults', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $40-$50 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 9 a.m. - 9:45 a.m. \n Student Recreation Center Pool', '2025-06-21 13:00:00', '2025-06-21 15:00:00', 1635, 'Student Recreation Center Pool'),
('Learn to Swim - 8 to 13 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 10:30 a.m. - 11:15 a.m. \n Student Recreation Center Pool', '2025-06-15 14:30:00', '2025-06-15 16:30:00', 1632, 'Student Recreation Center Pool'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 11:30 a.m. - 12:15 p.m. \n Student Recreation Center Pool', '2025-06-15 15:30:00', '2025-06-15 17:30:00', 1633, 'Student Recreation Center Pool'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 12 p.m. - 12:45 p.m. \n Student Recreation Center Pool', '2025-06-14 16:00:00', '2025-06-14 18:00:00', 1630, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - Adults ', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $40-$50 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 9:30 a.m. - 10:15 a.m. \n Student Recreation Center Pool', '2025-06-15 13:30:00', '2025-06-15 15:30:00', 1631, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 8 to 13 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 11 a.m. - 11:45 a.m. \n Student Recreation Center Pool', '2025-06-14 15:00:00', '2025-06-14 17:00:00', 1629, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 10 a.m. - 10:45 a.m. \n Student Recreation Center Pool', '2025-06-14 14:00:00', '2025-06-14 16:00:00', 1628, 'Student Recreation Center 1200 - Natatorium'),
('Safe Space Training', 'Advocacy and Outreach', 'Our Safe Space Training is an intensive, interactive training that provides attendees with information and tools to combat homophobia, biphobia, transphobia, cissexism and heterosexism, on campus and beyond. Through interactive activities and discussion, participants will personally reflect on their own experiences to enhance their personal and professional development, provide further education, and finally, identify ways to create change on campus and beyond. \n All sessions are three hours and are first-come, first-served. Pre-registration is required. Registrants are expected to attend the full session. Only individuals who have fully completed the Safe Space Program and have agreed to the expectations of its membership are able to display the sticker/button of our program. Refreshments are not provided, however, you are more than welcome to bring your lunch, coffee, snacks, etc.', '2025-06-10 18:00:00', '2025-06-10 20:00:00', 1626, 'STCT 419'),
('Learn to Swim - Adults', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $40-$50 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 9 a.m. - 9:45 a.m. \n Student Recreation Center Pool', '2025-06-14 13:00:00', '2025-06-14 15:00:00', 1627, 'Student Recreation Center Pool'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 11:30 a.m. - 12:15 p.m. \n Student Recreation Center Pool', '2025-06-08 15:30:00', '2025-06-08 17:30:00', 1624, 'Student Recreation Center Pool'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 12:30 p.m. - 1:15 p.m. \n Student Recreation Center Pool', '2025-06-08 16:30:00', '2025-06-08 18:30:00', 1625, 'Student Recreation Center Pool'),
('Learn to Swim - 8 to 13 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 10:30 a.m. - 11:15 a.m. \n Student Recreation Center Pool', '2025-06-08 14:30:00', '2025-06-08 16:30:00', 1623, 'Student Recreation Center Pool'),
('Learn to Swim - Adults ', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $40-$50 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 9:30 a.m. - 10:15 a.m. \n Student Recreation Center Pool', '2025-06-08 13:30:00', '2025-06-08 15:30:00', 1622, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 12 p.m. - 12:45 p.m. \n Student Recreation Center Pool', '2025-06-07 16:00:00', '2025-06-07 18:00:00', 1621, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 8 to 13 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 11 a.m. - 11:45 a.m. \n Student Recreation Center Pool', '2025-06-07 15:00:00', '2025-06-07 17:00:00', 1620, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - Adults', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $40-$50 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 9 a.m. - 9:45 a.m. \n Student Recreation Center Pool', '2025-06-07 13:00:00', '2025-06-07 15:00:00', 1618, 'Student Recreation Center Pool'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 10 a.m. - 10:45 a.m. \n Student Recreation Center Pool', '2025-06-07 14:00:00', '2025-06-07 16:00:00', 1619, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 11:30 a.m. - 12:15 p.m. \n Student Recreation Center Pool', '2025-06-01 15:30:00', '2025-06-01 17:30:00', 1616, 'Student Recreation Center Pool'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 12:30 p.m. - 1:15 p.m. \n Student Recreation Center Pool', '2025-06-01 16:30:00', '2025-06-01 18:30:00', 1617, 'Student Recreation Center Pool'),
('Learn to Swim - 8 to 13 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 10:30 a.m. - 11:15 a.m. \n Student Recreation Center Pool', '2025-06-01 14:30:00', '2025-06-01 16:30:00', 1615, 'Student Recreation Center Pool'),
('Learn to Swim - Adults ', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $40-$50 \n \n Where and when? \n \n Sunday, 06/01 - 06/22 \n 9:30 a.m. - 10:15 a.m. \n Student Recreation Center Pool', '2025-06-01 13:30:00', '2025-06-01 15:30:00', 1614, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 12 p.m. - 12:45 p.m. \n Student Recreation Center Pool', '2025-05-31 16:00:00', '2025-05-31 18:00:00', 1613, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 8 to 13 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 11 a.m. - 11:45 a.m. \n Student Recreation Center Pool', '2025-05-31 15:00:00', '2025-05-31 17:00:00', 1612, 'Student Recreation Center 1200 - Natatorium'),
('Learn to Swim - 5 to 8 Years Old', 'Campus Recreation', 'Our program focuses on the strengths and skills needed for swimming, and will help swimmers of all ages develop and refine their skills. Whether you already know how to swim or are just starting out, our classes will help you become a stronger swimmer and develop skills that will last a lifetime. Classes are taught under the watchful eye of our trained instructors, and include lessons on a variety of different strokes and techniques. Our program boasts an excellent instructor to student ratio, with one instructor for every 3 participants for beginner classes, and one instructor to five students at other levels. \n How do I sign-up? \n \n Register online throughÂ  Fusion , in the Student Recreation Center`s main office, or over the phone (973-655-3340). \n Cost - $64 - $80 \n \n Where and when? \n \n Saturdays, 05/31 - 06/21 \n 10 a.m. - 10:45 a.m. \n Student Recreation Center Pool', '2025-05-31 14:00:00', '2025-05-31 16:00:00', 1611, 'Student Recreation Center 1200 - Natatorium'),
('Fact-Checking And Misinformation', 'Sprague Library', 'This workshop will discuss the art of fact-checking sources. By learning to recognize bias, disinformation, and misinformation, you will gain the critical thinking skills vital for research and informed decision-making. \n Register Here:Â https://montclair.libcal.com/event/14525834', '2025-05-19 22:00:00', '2025-05-20 00:00:00', 1655, 'Sprague Library Instruction Room 203'),
('Research Time Management', 'Sprague Library', 'Research Time Management \n \n Research time management is an essential skillÂ for academic success. In this workshop, participants will: \n \n Learn the steps of the research process \n Create a research timeline \n Set SMART goals \n Learn strategies toÂ avoid procrastination \n Learn about library `shortcuts` \n \n Register Here:Â https://montclair.libcal.com/event/14525816', '2025-05-14 18:00:00', '2025-05-14 20:00:00', 1654, 'Sprague Library Instruction Room 203'),
('Embed Library Resources in Canvas', 'Sprague Library', 'In this hands-on session, you`ll learn how to quickly and easily embed library resources such as databases, journals, e-books, articles and streaming video into your Canvas course.Â We`ll walk you through permalinking and creating persistent links to prompt your students to log in and access library content hassle-free. We`ll also cover adding a librarian to your course and demonstrate the Library Resources tab in Canvas. \n Register Here:Â https://montclair.libcal.com/event/14544852', '2025-05-09 17:00:00', '2025-05-09 19:00:00', 1653, 'Online'),
('Spring Senior Dance Project', 'The College of the Arts', 'Directed by Christian von Howard \n Friday, May 2 @ 7:30 pm Saturday, May 3 @ 2:00 and 7:30 pm Sunday, May 4 @ 2:00 pm \n Life Hall Studio Theatre 1200 | FreeÂ  \n \n \n I acknowledge that RSVPing to this event does not substitute a physical ticket for entry. I understand I must acquire a physical ticket at The Alexander Kasser Theater Box Office before show time.', '2025-05-03 23:30:00', '2025-05-04 01:30:00', 1593, 'Life Hall Studio Theatre 1200'),
('Spring Senior Dance Project', 'The College of the Arts', 'Directed by Christian von Howard \n Friday, May 2 @ 7:30 pm Saturday, May 3 @ 2:00 and 7:30 pm Sunday, May 4 @ 2:00 pm \n Life Hall Studio Theatre 1200 | FreeÂ  \n \n \n I acknowledge that RSVPing to this event does not substitute a physical ticket for entry. I understand I must acquire a physical ticket at The Alexander Kasser Theater Box Office before show time.', '2025-05-04 18:00:00', '2025-05-04 20:00:00', 1594, 'Life Hall Studio Theatre 1200'),
('2025 OSJD Impact Awards: Celebrating Community, Service and Excellence', 'Advocacy and Outreach', 'We are proud to announce the `2025 OSJD Impact Awards: Celebrating Community, Service and Excellence` on Tuesday, May 6, 2025 at 5:30 p.m. in the University Hall Conference Center.Â  \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n Join us for a magical night as we recognize five outstanding members of our university community for their outstanding contributions to improving our campus experience for all. Open to all to attend! \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n Â  \n More details are provided in the nomination form. \n Â  \n Impact Awards nominations are due by Friday, March 7, 2025. Nomination Form:Â  HERE! \n Â  \n TO ATTEND, YOU MUST RSVP VIA THIS ENGAGE EVENT PAGE FOR YOURSELF AND UP TO 2 GUESTS!', '2025-05-06 22:00:00', '2025-05-07 00:00:00', 1596, 'University Hall Conference Center'),
('Spring Senior Dance Project', 'The College of the Arts', 'Directed by Christian von Howard \n Friday, May 2 @ 7:30 pm Saturday, May 3 @ 2:00 and 7:30 pm Sunday, May 4 @ 2:00 pm \n Life Hall Studio Theatre 1200 | FreeÂ  \n \n \n I acknowledge that RSVPing to this event does not substitute a physical ticket for entry. I understand I must acquire a physical ticket at The Alexander Kasser Theater Box Office before show time.', '2025-05-02 23:30:00', '2025-05-03 01:30:00', 1590, 'Life Hall Studio Theatre 1200'),
('Spring Senior Dance Project', 'The College of the Arts', 'Directed by Christian von Howard \n Friday, May 2 @ 7:30 pm Saturday, May 3 @ 2:00 and 7:30 pm Sunday, May 4 @ 2:00 pm \n Life Hall Studio Theatre 1200 | FreeÂ  \n \n \n I acknowledge that RSVPing to this event does not substitute a physical ticket for entry. I understand I must acquire a physical ticket at The Alexander Kasser Theater Box Office before show time.', '2025-05-03 18:00:00', '2025-05-03 20:00:00', 1591, 'Life Hall Studio Theatre 1200'),
('Product Design Senior Thesis 2025', 'The College of the Arts', 'https://www.youtube.com/watch?v=zXBzbNzjy2I', '2025-05-02 23:30:00', '2025-05-03 01:30:00', 1588, 'Presentation Hall, School of Communication and Media'),
('Friday Night Firepit', 'Campus Recreation', 'Hang out with your friends on Friday night around the fire pit!Â  Free snacks, such as s`mores and iced tea, will be provided.Â  Lawn games, hammocks, and other items will also be available FREE via Equipment Checkout.Â Â  \n How do I sign-up? \n \n Registration not required \n Free with Montclair State University ID \n \n Where and when? \n \n Friday, May 2 \n 7:00 pm - 9:00 pmÂ  \n Student Recreation Center', '2025-05-02 23:00:00', '2025-05-03 01:00:00', 1589, 'Student Recreation Center PATIO - Back Patio'),
('Study Hall', 'Sinatra Hall', 'Come hang out in the community lounge and study for finals with your Sinatra Hall Council! Free food and drinks while supplies last.', '2025-05-02 00:00:00', '2025-05-02 02:00:00', 1585, 'Francis A. Sinatra Hall'),
('Spring 2025 Product Design Thesis Showcase', 'Art and Design', 'ðŸŽ‰ Join us for the highly anticipated Spring 2025 Product Design Thesis Showcase! \n Â  \n ðŸ—“ï¸  May 2, 2025 ðŸ••  6:00 PM ðŸ“  School of Communication and Media, Presentation Hall \n Â  \n We are  thrilled  to invite you to an inspiring celebration of creativity, innovation, and the culmination of months of hard work by our incredibly talented Product Design seniors. ðŸŒŸ \n Â  \n Whether youâ€™re an industry pro scouting fresh talent, a design enthusiast looking for your next spark of inspiration, or just curious about what the future of product design looks likeâ€”this is the event for you! \n Â  \n âœ¨ Expect groundbreaking concepts ðŸŽ¤ Captivating presentations ðŸ” Engaging interactive Q&A \n Â  \n This is more than a showcaseâ€”itâ€™s a launchpad for the next generation of design leaders. Donâ€™t miss your chance to experience their vision, dedication, and design excellence up close.', '2025-05-02 22:00:00', '2025-05-03 00:00:00', 1587, 'School of Communication and Media, Presentation Hall '),
('Stupid F*cking Bird', 'The College of the Arts', 'Written by Aaron Posner Sort of Adapted from The Seagull by Anton Chekhov \n Directed by Cristina Angeles \n An aspiring young director rampages against the art created by his motherâ€™s generation. A nubile young actress wrestles with an aging Hollywood star for the affections of a renowned novelist. And everyone discovers just how disappointing love, art, and growing up can be. In this irreverent, contemporary, and very funny remix of Chekhovâ€™s The Seagull, Aaron Posner stages a timeless battle between young and old, past and present, in search of the true meaning of it all. Original songs composed by James Sugg draw the famously subtextual inner thoughts of Chekhovâ€™s characters explicitly to the surface. Stupid F*cking Bird will tickle, tantalize, and incite you to consider how art, love, and revolution fuel your own pursuit of happiness. \n Sat, Apr 26 @ 2:00 PM & 7:30 PM Thu, May 1 @ 7:30 PM; Fri, May 2 @ 7:30 PM; Sat, May 3 @ 2:00 PM & 7:30PM \n Â  \n I acknowledge that RSVPing to this event does not substitute a physical ticket for entry.  I understand I must acquire a physical ticket at The Alexander Kasser Theater Box Office before show time.', '2025-05-01 23:30:00', '2025-05-02 01:30:00', 1584, 'Memorial Auditorium'),
('L`Atelier Montclair: Threaded Awakening', 'The College of the Arts', 'MSU fashion show. Student designs, surreal dreams. \n This is our annual fashion show, a student-produced event showcasing garments created within our program`s curriculum. Proceeds from ticket sales will directly support our students and program, enabling us to continue our mission and vision. \n Tickets are $10: Get Tickets', '2025-05-01 21:00:00', '2025-05-01 23:00:00', 1582, 'Presentation Hall, School of Communication and Media'),
('Campus Earth Month', 'Office of Sustainability', 'The Montclair Office of Sustainability is launching a new tradition this April, Earth Month! \n Participate in Campus Earth Month throughout April by collecting code words and earning entries to win prizes.Â Each code word you collect or action you complete will earn you an entry into the Campus Earth Month giveaway.Â The more entries you earn, the better your odds.Â  \n You could win a Go Pro, a Yeti Cooler, $250 Red Hawk Dollars, a Nintendo Switch, and more!Â  \n Each decision you make has the potential to be good for the planet and people. No one can do it all, but we can all do something. This April, make sure your ledger is balanced so you are alwaysâ€¦+1 for the Planet! \n We hope to see you out on campus and Happy Earth Month, Red Hawks!', '2025-04-01 17:00:00', '2025-04-01 19:00:00', 1580, 'Online'),
('Stupid F*cking Bird', 'The College of the Arts', 'Written by Aaron Posner Sort of Adapted from The Seagull by Anton Chekhov \n Directed by Cristina Angeles \n An aspiring young director rampages against the art created by his motherâ€™s generation. A nubile young actress wrestles with an aging Hollywood star for the affections of a renowned novelist. And everyone discovers just how disappointing love, art, and growing up can be. In this irreverent, contemporary, and very funny remix of Chekhovâ€™s The Seagull, Aaron Posner stages a timeless battle between young and old, past and present, in search of the true meaning of it all. Original songs composed by James Sugg draw the famously subtextual inner thoughts of Chekhovâ€™s characters explicitly to the surface. Stupid F*cking Bird will tickle, tantalize, and incite you to consider how art, love, and revolution fuel your own pursuit of happiness. \n Â  \n Fri, April 25 @ 7:30 PM Sat, Apr 26 @ 2:00 PM & 7:30 PM Tue, April 29 @ 7:30 PM Wed, April 30 @ 7:30 PM Thu, May 1 @ 7:30 PM \n Â  \n I acknowledge that RSVPing to this event does not substitute a physical ticket for entry.  I understand I must acquire a physical ticket at The Alexander Kasser Theater Box Office before show time.', '2025-04-30 23:30:00', '2025-05-01 01:30:00', 1579, 'Memorial Auditorium'),
('Commuter Connect Program ', 'Bloomfield Student Life', 'Commuter Connect Program  is designed to support commuter students by fostering a sense of community and engagement on campus. Through mentorship, peer connections, and tailored events, the program helps commuters integrate into university life, access valuable resources, and build a support network that enhances both their academic and social experiences. It includes regular meetups, study groups, and workshops to ensure commuter students feel connected and supported throughout their time at the university.Â   Commuter Connect Signup Link:', '2024-10-04 15:00:00', '2024-10-04 17:00:00', 1578, 'Student Affairs '),
('Closing Reception of All Things Considered Exhibition', 'Art and Design', 'Celebrate the end of the year with this brilliant showcase from our rising Visual Arts graduates! This exhibition marks the culmination of their degree, launching their creative journeys. Each student presents a cohesive body of artwork in the Finley Galleries, our final exhibition of the Fall 2025 semester. Join us on Wednesday, April 30 at 6pm to meet the artists at the closing reception. \n Â  \n All Things Considered  features an impressive range of interdisciplinary approaches: mixed-media sculpture, large-scale painting, hand-sewn textiles, ceramics, video projection, photography, and room-sized installations. 45 Visual Arts graduates invite you to explore their creative research and current concerns, on view through these vibrant capstone projects!Â  On view from April 24 till April 30, 2025.Â  \n Exhibiting Artists: Section 1:  Santiago Arcila, Kelly Arita, Sabrina Gatti, Ian Hagen, Jiapsi Juarez-Cipriano, Bryana Martinez, Agnieszka Palka, Krisha Ravishankar, Jin Scheef, Anacia Sessoms, Walaa Shaabneh, Julea Sorrentino, Katie Weuste, Margo Wittlinger, Joseph Visco \n Section 2:  Jivon Batres, Nick Cruz, Genesis Garcia-Morales, Tevin Gomez, Lauryn Jeffrey, Bralen Jones, Aaron Leung, Emily Luh, Lara Maisonneuve, Gabriel Rodriguez, Amaya Tiozon, Sadie Vizcaino, Odessa Whitlock, Brendan Wilsea \n Â  \n Section 3:  Frankie Christie, Paola Cruz, Gina DeMartino, Marlena Holston, Gabriel Marano, Jonathan Muruzumbay, Quara Phillips-Hill, Edward Puello, Meghan Sibert, Brion Spruill, Antonia Sussina, Kimberly Triana Vallejo, Grace Whitteaker, Zoe Yeung, Cedric Yoo, Claudia Zuraw \n Â  \n All Things Considered BA Visual Arts Thesis Exhibition Finley Gallery, Finley Hall Exhibition dates: April 24-30, 2025 Closing Reception: Wednesday April 30, 6-8pm', '2025-04-30 22:00:00', '2025-05-01 00:00:00', 1576, 'Finley Gallery, Finley Hall'),
('All Things Considered - BA Visual Arts Thesis Exhibition', 'Art and Design', 'All Things Considered \n BA Visual Arts Thesis Exhibition \n Finley Gallery, Finley Hall \n Exhibition dates: April 24-30, 2025 \n Closing Reception: Wednesday April 30, 6-8pm \n Â  \n Celebrate the end of the year with this brilliant showcase from our rising Visual Arts graduates! This exhibition marks the culmination of their degree, launching their creative journeys. Each student presents a cohesive body of artwork in the Finley Galleries, our final exhibition of the Fall 2025 semester. Join us on Wednesday, April 30 at 6pm to meet the artists at the closing reception. \n Â  \n All Things Considered  features an impressive range of interdisciplinary approaches: mixed-media sculpture, large-scale painting, hand-sewn textiles, ceramics, video projection, photography, and room-sized installations. 45 Visual Arts graduates invite you to explore their creative research and current concerns, on view through these vibrant capstone projects!Â  On view from April 24 till April 30, 2025.Â  \n Exhibiting Artists: Section 1: Santiago Arcila, Kelly Arita, Sabrina Gatti, Ian Hagen, Jiapsi Juarez-Cipriano, Bryana Martinez, Agnieszka Palka, Krisha Ravishankar, Jin Scheef, Anacia Sessoms, Walaa Shaabneh, Julea Sorrentino, Katie Weuste, Margo Wittlinger, Joseph Visco \n Section 2: Jivon Batres, Nick Cruz, Genesis Garcia-Morales, Tevin Gomez, Lauryn Jeffrey, Bralen Jones, Aaron Leung, Emily Luh, Lara Maisonneuve, Gabriel Rodriguez, Amaya Tiozon, Sadie Vizcaino, Odessa Whitlock, Brendan Wilsea \n Â  \n Section 3: Frankie Christie, Paola Cruz, Gina DeMartino, Marlena Holston, Gabriel Marano, Jonathan Muruzumbay, Quara Phillips-Hill, Edward Puello, Meghan Sibert, Brion Spruill, Antonia Sussina, Kimberly Triana Vallejo, Grace Whitteaker, Zoe Yeung, Cedric Yoo, Claudia Zuraw', '2025-04-30 15:00:00', '2025-04-30 17:00:00', 1575, 'Finley Gallery, Finley Hall'),
('General Body Meetings', 'The Women Of Color Alliance ', 'The members of WOCA gather as a community on campus and share information', '2025-04-30 18:00:00', '2025-04-30 20:00:00', 1573, 'University Hall 2010 - Classroom'),
('Robotics Club Final Meeting', 'Montclair State University Robotics Club', 'Join the Robotics Club for our final meeting of the semester where we`ll celebrate our members` achievements with food and prizes. Don`t miss out!', '2025-04-30 18:00:00', '2025-04-30 20:00:00', 1571, 'CELS 120'),
('General Body Meeting', 'Epsilon Delta Epsilon', 'This is a general body meeting for EDE members.', '2025-04-30 18:00:00', '2025-04-30 20:00:00', 1570, 'School Of Business 220 - Flexible Standard Classroom'),
('Write Your Own Story Workshop Series', 'Bloomfield Student Life', '` Write Your Own Story Writing Workshop`', '2025-02-26 18:00:00', '2025-02-26 20:00:00', 1568, 'Bloomfield College Library '),
('Study Hall', 'Sinatra Hall', 'Come hang out in the community lounge and study for finals with your Sinatra Hall Council! Free food and drinks while supplies last.', '2025-04-30 00:00:00', '2025-04-30 02:00:00', 1564, 'Francis A. Sinatra Hall');
INSERT INTO `events` (`Name`, `Organization`, `Description`, `TimeStart`, `TimeEnd`, `EID`, `Location`) VALUES
('Embed Library Resources in Canvas', 'Sprague Library', 'In this hands-on session, you`ll learn how to quickly and easily embed library resources such as databases, journals, e-books, articles and streaming video into your Canvas course.Â We`ll walk you through permalinking and creating persistent links to prompt your students to log in and access library content hassle-free. We`ll also cover adding a librarian to your course and demonstrate the Library Resources tab in Canvas. \n \n RelatedÂ LibGuide:Â  Canvas and Library Integration by Bill Vincenti \n Register Here:Â https://montclair.libcal.com/event/14544735', '2025-05-05 14:30:00', '2025-05-05 16:30:00', 1651, 'Online'),
('Denim Day 2025: Mind the Gaps, Move Forward', 'University Police Department', 'April is Sexual Assault Awareness Month, and together, we can break the silence.  The Montclair State University Police Department and the Office for Social Justice and Diversity are committed to fostering a campus where survivors feel heard, supported, and empowered.  It starts with believing. It starts with you.  By offering a safe and affirming response to those who disclose gender-based and sexual violence, we can create lasting change. Letâ€™s stand together to end the cycle of silenceâ€”because  every voice matters, and every action counts \n Denim Day is recognized internationally as a day of action and awareness, encouraging people to wear denim to challenge victim-blaming and educate others about sexual violence.  This year, Denim Day falls on Wednesday, April 30, 2025. \n The University Police and  Office for Social Justice and Diversity and the newly formed Office of Advocacy and Community Resilience , in partnership with over 30 campus and local community organizations, invites you to join us  from 9 a.m. to 12 p.m. at the Amphitheater  for a powerful awareness event honoring survivors and increasing awareness of available resources. \n Despite the  gaps  that still exist in the criminal justice system, in resources, and in prevention education,  we will move forward together  as a community. As part of this commitment, we will walk  one mile around campus in solidarity with survivors.', '2025-04-30 13:00:00', '2025-04-30 15:00:00', 1566, 'Meet at the Amphitheater'),
('Rec Nights - Denim Day Decorating', 'Campus Recreation', 'Every year, Denim Day is observed to raise awareness of sexual assault in general among both participants and the general public. Join us as we celebrate Denim Day by decorating everything denim and learning more about its history. Bring your own denim objects to embellish or select from our selection of hats and bags made of denim. \n \n \n How do I sign-up? \n \n Registration is not required \n FREE for students with a valid Montclair State ID \n \n Where and when? \n \n Tuesday, April 29 \n 7pm-9pm, must be checked in by 8:30pm to participate \n Student Recreation Center Lounge', '2025-04-29 23:00:00', '2025-04-30 01:00:00', 1562, 'Student Recreation Center 11C2A - Lobby Lounge'),
('Stupid F*cking Bird', 'The College of the Arts', 'Written by Aaron Posner Sort of Adapted from The Seagull by Anton Chekhov \n Directed by Cristina Angeles \n An aspiring young director rampages against the art created by his motherâ€™s generation. A nubile young actress wrestles with an aging Hollywood star for the affections of a renowned novelist. And everyone discovers just how disappointing love, art, and growing up can be. In this irreverent, contemporary, and very funny remix of Chekhovâ€™s The Seagull, Aaron Posner stages a timeless battle between young and old, past and present, in search of the true meaning of it all. Original songs composed by James Sugg draw the famously subtextual inner thoughts of Chekhovâ€™s characters explicitly to the surface. Stupid F*cking Bird will tickle, tantalize, and incite you to consider how art, love, and revolution fuel your own pursuit of happiness. \n Â  \n Fri, April 25 @ 7:30 PM Sat, Apr 26 @ 2:00 PM & 7:30 PM Tue, April 29 @ 7:30 PM Wed, April 30 @ 7:30 PM Thu, May 1 @ 7:30 PM \n Â  \n I acknowledge that RSVPing to this event does not substitute a physical ticket for entry.  I understand I must acquire a physical ticket at The Alexander Kasser Theater Box Office before show time.', '2025-04-29 23:30:00', '2025-04-30 01:30:00', 1563, 'Memorial Auditorium'),
('Spoken Word Night', 'Montclair State University Galleries', 'Meet the artist Layo Bright and come together to share your stories through spoken word, written reflection, and simply listening. This is a space to express yourself freely, connect with others, and celebrate our experiences in the context of the University Galleries` current exhibition  Invasive   Blooms . Writing materials & supplies will be provided. \n About the Exhibition on view Through sculpture, artist Layo Bright delves into themes of time, feminism, migration, and the African diaspora. Her practice employs blown, fused, and cast glass processes, along with mixed media, such as textiles, wood, and ceramics, to engage ideas about individual and community identity. \n This exhibition features recent and new works, including the debut of an hourglass sculpture that marks the passage of time and Bloom portraits created in collaboration with the Montclair State University community. These portraits incorporate casts of faces of students, faculty, and staff, accompanied by their migration stories and reflections on identity, traditions, beliefs, and empowerment.  Learn more', '2025-04-29 22:30:00', '2025-04-30 00:30:00', 1561, 'Kasser Theater Lobby'),
('Picnic Paint and Sip', 'Office of Student Belonging', 'Unwind from finals with the Office of Student Belonging for a Picnic Paint and Sip! Enjoy a relaxing day outdoors with friends. All students are welcome!', '2025-04-29 17:00:00', '2025-04-29 19:00:00', 1557, 'The Student Center Quad/Ballroom C (Rain Location)'),
(' Integrative Studio II Student-led Exhibitions - One day, Three Locations', 'Art and Design', 'ðŸŽ¨âœ¨ Youâ€™re invited to the Integrative Studio II Student-led Exhibitions! \n Â  \n Presented by the Department of Art & Design, this one-day, three-location event features powerful work from students in collaboration with Professors Jess Blaustein, Simone Couto, and Genevieve Lowe. \n Â  \n ðŸ—“ï¸  Tuesday, April 29, 2025 ðŸ•‘  2:00â€“4:00 PM ðŸ“  Three unique exhibitions across campus \n Â  \n ðŸ”»  SECTION 01: Awakening Visions ðŸ“  Student Center Quad 1 Exploring identity, gender, desire, suffering, and transcendence through deeply personal and collective perspectives. \n Â  \n ðŸ”»  SECTION 02: Elevate ðŸ“  School of Communication Lobby Staircase A reflection on growth, experimentation, and the evolving practice of becomingâ€”artistically and individually. \n Â  \n ðŸ”»  SECTION 03: Labyrinths of Matter ðŸ“  Memorial Auditorium Courtyard An immersive journey through materiality, emotion, and meaningâ€”get lost and discover something within. \n Â  \n Come walk the campus, meet the artists, and experience a vibrant range of voices, visions, and mediums. ðŸŽ­ðŸ–¼ï¸ðŸŒ€', '2025-04-29 18:00:00', '2025-04-29 20:00:00', 1558, 'Student Center Quad 1, School of Communication Lobby Staircase, & Memorial Auditorium Courtyard'),
('Letter Writing for the Planet', 'Office of Sustainability', 'a', '2025-04-29 16:00:00', '2025-04-29 18:00:00', 1555, 'stct 160'),
('CPT Workshop - International Students (F-1 Visa Holders) Only', 'Office of Global Engagement', 'For students who are planning to apply for CPT for the summer or fall 2025 semesters. Learn more about Curricular Practical Training (CPT) for F-1 students. Any student planning to apply for CPT is REQUIRED to attend a workshop before they can apply. This workshop is for CURRENT students ONLY - any other attendees will be removed.', '2025-04-29 15:00:00', '2025-04-29 17:00:00', 1553, 'Online'),
('All Things Considered - BA Visual Arts Thesis Exhibition', 'Art and Design', 'All Things Considered \n BA Visual Arts Thesis Exhibition \n Finley Gallery, Finley Hall \n Exhibition dates: April 24-30, 2025 \n Closing Reception: Wednesday April 30, 6-8pm \n Â  \n Celebrate the end of the year with this brilliant showcase from our rising Visual Arts graduates! This exhibition marks the culmination of their degree, launching their creative journeys. Each student presents a cohesive body of artwork in the Finley Galleries, our final exhibition of the Fall 2025 semester. Join us on Wednesday, April 30 at 6pm to meet the artists at the closing reception. \n Â  \n All Things Considered  features an impressive range of interdisciplinary approaches: mixed-media sculpture, large-scale painting, hand-sewn textiles, ceramics, video projection, photography, and room-sized installations. 45 Visual Arts graduates invite you to explore their creative research and current concerns, on view through these vibrant capstone projects!Â  On view from April 24 till April 30, 2025.Â  \n Exhibiting Artists: Section 1: Santiago Arcila, Kelly Arita, Sabrina Gatti, Ian Hagen, Jiapsi Juarez-Cipriano, Bryana Martinez, Agnieszka Palka, Krisha Ravishankar, Jin Scheef, Anacia Sessoms, Walaa Shaabneh, Julea Sorrentino, Katie Weuste, Margo Wittlinger, Joseph Visco \n Section 2: Jivon Batres, Nick Cruz, Genesis Garcia-Morales, Tevin Gomez, Lauryn Jeffrey, Bralen Jones, Aaron Leung, Emily Luh, Lara Maisonneuve, Gabriel Rodriguez, Amaya Tiozon, Sadie Vizcaino, Odessa Whitlock, Brenda Wilsea \n Â  \n Section 3: Frankie Christie, Paola Cruz, Gina DeMartino, Marlena Holston, Gabriel Marano, Jonathan Muruzumbay, Quara Phillips-Hill, Edward Puello, Meghan Sibert, Brion Spruill, Antonia Sussina, Kimberly Triana Vallejo, Grace Whitteaker, Zoe Yeung, Cedric Yoo, Claudia Zuraw', '2025-04-29 15:00:00', '2025-04-29 17:00:00', 1554, 'Finley Gallery, Finley Hall'),
('Gathering Your Sources: How to Use Library Resources to Find the Information You Need', 'Sprague Library', 'This workshop will highlight how to access different kinds of information through the Montclair State University Libraries, including books, newspaper articles, and scholarly publications. Perfect for those new to library research in a university setting. \n Register Here:Â https://montclair.libcal.com/event/14379758', '2025-04-30 13:15:00', '2025-04-30 15:15:00', 1650, 'Sprague Library Instruction Room 203'),
('HABLAMOS ESPAÃ‘OL - Spanish Conversation MeetUps', 'Center for Latino Heritage & Spanish Language Excellence', 'HABLAMOS ESPAÃ‘OL is back!  Informal Spanish conversations to help you improve your Spanish speaking skills are  now offered on Monday, Wednesday and Friday \n Different topic to chat about every week announced on  our Instagram page at #Montclair_CLaSE Â  \n All level are welcome! \n No need to reserve your spot. Show up at Schmitt Hall 135 but please check the schedule. \n Join us, learn more Spanish and meet people `hablando espaÃ±ol`!', '2025-01-30 17:00:00', '2025-01-30 19:00:00', 1643, 'Montclair State University - Schmitt Hall 138'),
('BCMSU`s Creative & Research Showcase: A Campus-Wide Celebration of Student Achievement', 'Bloomfield Center for Student Leadership & Engagement (CSLE)', 'a campus-wide celebration of student achievement across disciplines. This day-long event will feature presentations, performances, and exhibitions highlighting the work of our talented students acrossÂ the disciplines.', '2025-05-01 16:00:00', '2025-05-01 18:00:00', 1644, 'Westminster Hall'),
('Spanish Writing Center Tutoring Hours', 'Center for Latino Heritage & Spanish Language Excellence', 'Our Spanish Writing Center at CLaSE (Center for Latino heritage and Spanish language Excellence) is now offering  more  tutoring hours online and in-person starting  February 3rd . Our amazing tutors are Lorena Tacle and Ivan Podobed. If you need to improve you writing skills in Spanish, polish your written structures, or get help with your paper, article, letter, etc. check our tutors availability and book an appointment in our website https://www.montclair.edu/clase/our-initiatives/spanish-writing-center/', '2025-02-03 17:00:00', '2025-02-03 19:00:00', 1645, 'Online'),
('Greek Council', 'Greek Council', 'Weekly meeting for Greek Council, that governs of the Greek Letter organizations, and is an entity of the Office of Greek Life and Montclair State University.', '2025-04-29 21:30:00', '2025-04-29 23:30:00', 1657, 'STCT 411-414');

-- --------------------------------------------------------

--
-- Table structure for table `organizations`
--

CREATE TABLE `organizations` (
  `OrgID` int(11) NOT NULL,
  `OrgName` varchar(75) NOT NULL,
  `OrgDescription` varchar(250) NOT NULL,
  `OrgEmail` varchar(30) NOT NULL,
  `OrgPassword` varchar(42) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `organizations`
--

INSERT INTO `organizations` (`OrgID`, `OrgName`, `OrgDescription`, `OrgEmail`, `OrgPassword`) VALUES
(10, 'The Crazy Ones', 'tco', 'tco@gmail.com', '6c2eb69ec0d8814219d51bad4fa17b5c36a194eb'),
(11, 'LASSO', 'lasso test', 'lasso@gmail.com', '999504eeab02b73006e7547501c9671e6f2bc8d0'),
(13, 'soccer', 'edit', 'soccer@gmail.com', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220'),
(14, 'Montclair State University Galleries', 'An organization of Montclair State University', '75017252e2038c0b@gmail.com', 'e122b2930e73d73ee6897b7df48f725130dea7a1'),
(44, 'Sprague Library', 'An organization of Montclair State University', 'c6f95331238baeca@gmail.com', '871ab9299568005c'),
(19, 'Office of Global Engagement', 'An organization of Montclair State University', 'b2fbe6f2b6ab5a1a@gmail.com', 'e13cf10fcb30da58'),
(20, 'Art and Design', 'An organization of Montclair State University', 'ee294551ea706d02@gmail.com', '28d170a17fa0b2e6'),
(21, 'Office of Sustainability', 'An organization of Montclair State University', '4c8ae3ab699b8402@gmail.com', 'fc0ce8f9d65e07e1'),
(22, 'Office of Student Belonging', 'An organization of Montclair State University', '0f5de05ccba50218@gmail.com', 'b7a498781116069a'),
(45, 'Greek Council', 'An organization of Montclair State University', 'b5953538cca51a71@gmail.com', '18ccc127aa602405'),
(24, 'Montclair State University Galleries', 'An organization of Montclair State University', '75017252e2038c0b@gmail.com', 'a6672cca58cb2d0b'),
(25, 'Campus Recreation', 'An organization of Montclair State University', '16ed9e99f956e0d7@gmail.com', '7fc070df6f2c2d65'),
(26, 'The College of the Arts', 'An organization of Montclair State University', '9436e72eecbc380f@gmail.com', 'ef7fa766e981937d'),
(27, 'Sinatra Hall', 'An organization of Montclair State University', '06aaa779f6b4a9f6@gmail.com', 'a958b8dc35778f01'),
(28, 'University Police Department', 'An organization of Montclair State University', '7f775ac4882d01aa@gmail.com', 'f05b7a408cfdbced'),
(29, 'Center for Latino Heritage & Spanish Language Excellence', 'An organization of Montclair State University', '496a5297e54b2a65@gmail.com', '70461905e65f4314'),
(30, 'Bloomfield Student Life', 'An organization of Montclair State University', 'eb8c652e46421069@gmail.com', '4db41b5e90641f48'),
(32, 'Epsilon Delta Epsilon', 'An organization of Montclair State University', '6164acba1a855303@gmail.com', 'a4b473032ac209de'),
(33, 'Montclair State University Robotics Club', 'An organization of Montclair State University', 'd55a3b777e30f826@gmail.com', '8973286fb807010a'),
(35, 'The Women Of Color Alliance ', 'An organization of Montclair State University', '2dc05c1b57b120d8@gmail.com', '3e9e641e251a4440'),
(36, 'InterVarsity Christian Fellowship', 'An organization of Montclair State University', 'fde1b46c3ef40f1d@gmail.com', '493625e62fb4324c'),
(37, 'Bloomfield Center for Student Leadership & Engagement (CSLE)', 'An organization of Montclair State University', '0d91f5e6015257a8@gmail.com', '207e9500466f010d'),
(38, 'Higher Education Student Council', 'An organization of Montclair State University', 'c47dfcf31351cc6c@gmail.com', 'ae012ed1d8d7d7c2'),
(40, 'Advocacy and Outreach', 'An organization of Montclair State University', '2a5b19fbf0f7141d@gmail.com', '83c05754b41ad1ff'),
(41, 'The Crazy Ones', 'tco', 'tco@gmail.com', '8a03bacac31a85f837ffd7a022aec64a6f2be376'),
(42, 'test \'--', 'test\'', 'test\'@gmail.com', 'd4a7861369bff82aecb30e18cfeae82286836930');

-- --------------------------------------------------------

--
-- Table structure for table `rsvps`
--

CREATE TABLE `rsvps` (
  `UID` int(11) NOT NULL,
  `EID` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `rsvps`
--

INSERT INTO `rsvps` (`UID`, `EID`) VALUES
(8, 12),
(8, 1641),
(22, 1),
(22, 7),
(22, 1597),
(22, 1636),
(22, 1641),
(29, 16),
(29, 17),
(31, 15),
(31, 17),
(35, 1560);

-- --------------------------------------------------------

--
-- Table structure for table `schedules`
--

CREATE TABLE `schedules` (
  `UID` int(11) NOT NULL,
  `EventName` varchar(40) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `UID` int(11) NOT NULL,
  `FirstName` text NOT NULL,
  `LastName` text NOT NULL,
  `Email` varchar(42) NOT NULL,
  `Password` varchar(42) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`UID`, `FirstName`, `LastName`, `Email`, `Password`) VALUES
(10, '', '', '', 'da39a3ee5e6b4b0d3255bfef95601890afd80709'),
(16, 'hello', 'world', '1234@gmail.com', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220'),
(11, 'cristian', 'arcentales', 'arcentalesc1@montclair.edu', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220'),
(23, 'cristian', 'arcentales', 'arcentalescristian@gmail.com', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220'),
(21, '1234', '1234', 'asdf@gmail.com', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220'),
(12, 'Hacker', 'Jeff', 'HackerJ1@hacking.evil', '9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684'),
(13, 'Hacker', 'Jeff', 'HackerJ2@hacking.evil', 'd7cd56f2a2a3f47830760edfb89946eb7b9e2cd1'),
(14, 'Hacker', 'Jeff', 'HackerJ3@hacking.evil', '993376e3dcc84a0c11306eb2610b823af756216b'),
(15, 'Hacker', 'Jeff', 'HackerJ4@hacking.evil', '368f976940775c710aec525fe1e349f8a1fb9a39'),
(8, 'Ian', 'Love', 'ianklove88@gmail.com', '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8'),
(25, 'Jef', 'Kou', 'jef@kou.com', '570abe7bd720d88aa49523f5415e314bc50875a1'),
(18, 'jek', 'lastname', 'jek@mail.com', 'f63f66ddf9a2a405b9f9f44e93b3e6e34cae06ae'),
(33, 'Jiggy', 'Man', 'jman@gmail.com', '356a192b7913b04c54574d18c28d46e6395428ab'),
(34, 'James', 'Test', 'Jtest@gmail.com', '51abb9636078defbf888d8457a7c76f85c8f114c'),
(20, 'first', 'last', 'mail@mail', '86f7e437faa5a7fce15d1ddcb9eaeaea377667b8'),
(19, 'first', 'last', 'mail@mail.com', '3cbcd90adc4b192a87a625850b7f231caddf0eb3'),
(9, 'MArk', 'Jacobs', 'markj@gmail.com', '2aa60a8ff7fcd473d321e0146afd9e26df395147'),
(29, 'first', 'last', 'Test1@mail.com', 'c46f9f132864b7715255f22eede21f4d85685fdf'),
(31, 'first', 'last', 'Test2@mail.com', 'c46f9f132864b7715255f22eede21f4d85685fdf'),
(32, 'first', 'last', 'Test3@mail.com', 'c46f9f132864b7715255f22eede21f4d85685fdf'),
(22, 'Testing', 'Tester', 'test@test.com', '4c0d2b951ffabd6f9a10489dc40fc356ec1d26d5'),
(17, 'Test', 'TestLast', 'testuser@gmail.com', '8bb6118f8fd6935ad0876a3be34a717d32708ffd'),
(36, 'first', 'last', 'TestUser@mail.com', 'd8f161c093b211c6422802b41fc656a8e5f4e8b0'),
(35, 'User', '1', 'user@gmail.com', '7288edd0fc3ffcbe93a0cf06e3568e28521687bc');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admins`
--
ALTER TABLE `admins`
  ADD PRIMARY KEY (`AID`,`email`);

--
-- Indexes for table `events`
--
ALTER TABLE `events`
  ADD PRIMARY KEY (`EID`);

--
-- Indexes for table `organizations`
--
ALTER TABLE `organizations`
  ADD PRIMARY KEY (`OrgID`,`OrgEmail`);

--
-- Indexes for table `rsvps`
--
ALTER TABLE `rsvps`
  ADD PRIMARY KEY (`UID`,`EID`);

--
-- Indexes for table `schedules`
--
ALTER TABLE `schedules`
  ADD PRIMARY KEY (`UID`,`EventName`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`Email`),
  ADD UNIQUE KEY `UID` (`UID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admins`
--
ALTER TABLE `admins`
  MODIFY `AID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `events`
--
ALTER TABLE `events`
  MODIFY `EID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1658;

--
-- AUTO_INCREMENT for table `organizations`
--
ALTER TABLE `organizations`
  MODIFY `OrgID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=46;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `UID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
